export const data1 = [
    {
        title: "Driveway Cleaning",
        category: "domestic",
        price: 350,
        duration: 3,
        shift: ["morning", "day"],
        shiftCredit: 5,
        img: "",
        info: "Use a hose or pressure washer to remove all leaf matter and debris. Apply the organic detergent to the damp concrete and let it sit for 10 to 15 minutes. Scrub vigorously with a stiff broom or scrub brush. Rinse and repeat the process if necessary",
        rating: [],
    },
    {
        title: "Roof Cleaning",
        category: "domestic",
        price: 380,
        duration: 3,
        shift: ["morning", "day"],
        shiftCredit: 5,
        img: "",
        info: "Roof cleaning is the process of removing algae, mold, mildew, lichen and moss from roofs. Also cleaning oxidation on metal roofs. Cleaning can extend the duration of a roof's ability to function.",
        rating: [],
    },
    {
        title: "Graffiti Cleaning",
        category: "commercial",
        price: 750,
        duration: 8,
        shift: ["day"],
        shiftCredit: 10,
        img: "",
        info: "Try wiping graffiti with any common paint thinner (i.e. mineral spirits, lacquer thinner, acetone), or try graffiti removal products such as Goof Off. Sometimes wiping the graffiti with light penetrating oil such as WD-40 or Three-in-One will remove it.",
        rating: [],
    },
    {
        title: "Brick Cleaning",
        category: "commercial",
        price: 750,
        duration: 8,
        shift: ["day"],
        shiftCredit: 10,
        img: "",
        info: "Mix equal parts vinegar and water and pour into a spray bottle. Spray on the bricks and let is sit for a few minutes. Use a sponge mop to clean the bricks. If the bricks are very dirty, use a nylon-bristled scrub brush and put some elbow grease into the scrubbing.",
        rating: [],
    },
    {
        title: "Factory Cleaning",
        category: "industrial",
        price: 1200,
        duration: 8,
        shift: ["day"],
        shiftCredit: 10,
        img: "",
        info: "Industrial pressure washer cleaners is a high pressure reciprocating plunger pump that uses high pressure water jet to remove mold, grime, dust, mud and dirt from surfaces and objects such as buildings, vehicles and concrete road surfaces. A pressure washer is also known as power pressure washer.",
        rating: [],
    },
    {
        title: "Building and Walls",
        category: "industrial",
        price: 1200,
        duration: 8,
        shift: ["day"],
        shiftCredit: 10,
        img: "",
        info: "Pressure washers for building exteriors use hot water, cold water, and steam from a pump to completely remove dirt safely and efficiently. Sometimes, soaps and other cleaning agents are also used.",
        rating: [],
    },
]